### PR TITLE
Multiple keyboards

### PR DESCRIPTION
**Pull request by valrus**
This PR enables support for multiple keyboards. See the end of the README for a summary of how to handle multiple keyboards. (The process described should also work for multiple layouts for a single keyboard, though I haven't tried that.)

### CODE REVIEW

**Comment by mihaiolteanu** [comment]
Are you using an Atreus?

**Comment by valrus** [comment]
Yes to both, depending what you mean by "at the same time." I'm using an Ergodox and an Atreus with different machines but generating the layouts for them both from the same mugur setup.

**Comment by mihaiolteanu** [comment]
Oh, nice, I haven't expected that answer :)
I'll have to look into more detail into this, and also play with the code generation, but out of the top of my head, I would rather we avoid the added complexity, somehow.

That is, have a wiki, or something like that, with all the supported qmk-powered keyboards and the user can pick and copy/paste the template for his keyboard. I've tried to do that at the beginning of the project, actually, but I eventually ended up doing something straightforward that I could use now, instead of something generic that will never be done and that I'll never use (I 'only' have an Ergo and I'm not planning on trying anything else at the moment). I saw that each keyboard has it's own peculiarities. The fact that you can use the same layout for both Ergo and Atreus by some hack is nice, but what happens when the next keyboard comes in? Another such hack?

I'm totally open on making this a generic qmk keyboard generator, but I haven't managed to find the right solution that is also easy to use and doesn't add unnecessary clutter that most users won't need (extra files with templates for tens of keyboards, for example).

I will leave this open for the moment and I'll definitely revisit it for further comments.
If other users have any other input, that would also help.

**Comment by valrus** [comment]
Understandable, it's probably not a common use case and the design is a bit crude (I was also trying to do something straightforward that I could use now 😃).

That said, let me try to answer a couple of your questions / comments:
> The fact that you can use the same layout for both Ergo and Atreus by some hack is nice, but what happens when the next keyboard comes in? Another such hack?

I suppose, but each keyboard with a different layout will need something like another `mugur--layout-vertical` to represent its layout no matter how you do it; at some point, you need to hack the physical layout of the keyboard into the code somehow. The approach I took to use the same layout for both keyboards is not substantially different from how it would be done if I wanted to use a completely different layout for the Atreus; just the numbers in the format string would change.

> have a wiki, or something like that, with all the supported qmk-powered keyboards and the user can pick and copy/paste the template for his keyboard

I think my implementation would be compatible with this approach. The wiki would just need to have definitions of different arguments for the `:layout` keyword argument to `mugur-keymap`.

> I haven't managed to find the right solution that is also easy to use and doesn't add unnecessary clutter that most users won't need (extra files with templates for tens of keyboards, for example)

I did try to push as much of the complexity for the extra keyboard into the user's config rather than mugur itself, so that:
1. configs using the current mugur would continue to work with no changes, and hacking in a second layout as I did could be totally ignored by all but the small subset of users with more than one QMK keyboard
2. users would be responsible for defining their own layouts for different keyboards, so you wouldn't have to roll those extra templates into this repo

But it makes sense to me not to want to add complexity for this case: even if much of that complexity is in the user config, that might just mean you get more questions from multiple-keyboard users less comfortable with elisp, and they could be annoying to have to respond to since that's not your use case. So if you end up rejecting this PR, that makes sense to me, and I'm fine maintaining my fork if need be.

**Comment by mihaiolteanu** [comment]
Of course, you definitely need a new layout for each keyboard. I was trying to do a generic implementation initially, keep each keyboard layout template in a different file, and the user would specify the type of keyboard in `mugur-keymap` (something like you did). But there are so many keyboards and variations that I was not sure how to do it cleanly.

So now I'm thinking something like, ok, Ergodox is the default, if you want something different, just replace `mugur--layout-vertical` and `mugur--layout-horizontal` with what you have, and implement your `mugur-keymap` accordingly without changing its interface and implementation in any way. And if there are any problems, open a ticket and we can polish the rough edges to make this simpler. So far, you're the only user to have asked for a different keymap.

I would have also assumed that if you have different keyboards, you also have different approaches regarding their use. That is, not only remove the top row and keep everything in place, but if you have only one thumb button instead of three, you would want to compensate that by adapting the other keys. It is my understanding, that at least in your case, you do not want to create a keymap from scratch for each of your keyboards. If that would be the case, though, the above approach where you would just change the `mugur--layout-..." would work, in my mind.

I think we also do not have enough use-cases to figure out what the best approach is. I do not mind changing my config file to adapt to other keyboards (as this was initially my case), but I can honestly say I do not know what the best approach is.

**Comment by nico202** [comment]
Any news on this? I'd like to try mugur with my moonlander :)

**Comment by valrus** [comment]
You could use my fork: https://github.com/valrus/mugur
It's been working for me okay. Here's my current example, with config for an Ergodox and an Atreus: https://github.com/valrus/doom-private-module/blob/master/%2Bkeyboard.el

**Comment by mihaiolteanu** [comment]
Nicolò, you mean you would also want the option of using two keyboards (Ergodox EZ and the Moonlander in this case) with the same config? Please give more details of what you have in mind.

**Comment by nico202** [comment]
Yeah sorry for not being clear.  I want to use a single keyboard (the moonlander).  However, mugur currently hardcodes a few things that make it difficult:
https://github.com/mihaiolteanu/mugur/blob/34dfba027bf11e4cca2c547ce80b73d7324c7ba6/mugur.el#L1032
https://github.com/mihaiolteanu/mugur/blob/34dfba027bf11e4cca2c547ce80b73d7324c7ba6/mugur.el#L1041
(the moonlander uses a .bin file, else willy won't flash it)
https://github.com/mihaiolteanu/mugur/blob/34dfba027bf11e4cca2c547ce80b73d7324c7ba6/mugur.el#L946
and I guess a few others.

valrus partially address those, so I thought it could be a nice starting point

**Comment by mihaiolteanu** [comment]
Yes, but he wants to use two different keyboards at the same time, which would be a different implementation than just being able to use multiple keyboards. Everybody wants different things in life.

```
(the moonlander uses a .bin file, else willy won't flash it)
...
and I guess a few others.
```

Yes, that's what I'm afraid of. Each and every keyboard has a different way of doing things (that is, besides the different keyboard layouts). I'm still not sure what would be the common denominator catching them all, and still retain some sort of common ground and generality between them.

I would say that at the moment I do not plan to extend the functionality, to include the Moonlander, for example.
If you want to fork it and try it out as Ian did, feel free.
I can help you with clarifications and hints if/where the code is not so clear.

Yes, it would be nice to have one project that caches all the keyboards out there, and I would gladly help with that.
But I'm not sure who is gonna implement, do the bugfixes and maintain all those keyboards. I personally only have an Ergodox and I'm quite please with it, so I'm not planning on buying the Moonlander or any other keyboard. I'm more interested in actually using it than endlessly configuring it.

Do you have both? If so, do you find any improvements over the Ergodox?

**Comment by nico202** [comment]
> Do you have both? If so, do you find any improvements over the Ergodox?
Unfortunately not

> Yes, it would be nice to have one project that caches all the keyboards out there, and I would gladly help with that.
I guess I'll make this work for my keyboard and if I succeed I'll open a PR.  If we cannot find a common ground, living with separate forks is fine

> I'm more interested in actually using it than endlessly configuring it.
Nice point, mine is still new and I have still to configure it properly

**Comment by mihaiolteanu** [comment]
@nico202 you can try the latest mugur version 2.0 for your moonlander.
It should support any QMK keyboard, by default.

**Comment by nico202** [comment]
Wonderful! It did work (I've not flashed the output hex since I've just tried your example, but looks promising :) )
Thanks a lot for your work

**Comment by mihaiolteanu** [comment]
Now you'll just need to create your own moonlander keymap, and give it a try.
You can inspect the keymap.c before flashing, if you really want.

Specifically, the example is just that, an example of what I'm using. It is not really meant to be used, especially on a different keyboard type.

Let me know how it works!

**Comment by mihaiolteanu** [comment]
...and many thanks for the tickets and PRs!

**Comment by nico202** [comment]
> Now you'll just need to create your own moonlander keymap, and give it a try.
I already ported 2 layers of my current setup and it works fine!  Still have to figure out how oryx does something in order to fix a couple of keys, but overall the experience is wonderful :)

**Pull request closed without merging**
